[project]
name = "image-transform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "awswrangler>=3.9.1",
    "pytest>=8.3.3",
    "rembg>=2.0.59",
]
